### ISSUE TITLE
example on how to use the re-director server and geo ip location

### ISSUE THREAD

**Issue by alecmoran1** [outflanknl/RedELK#10]
Thanks for putting this together. Much, much appreciated. I was able to fix another problem I had. But, I was curious why my beacons location is not showing up on the map. Is there something I need to add to the script? Also, I haven't added anything to the redirector, I appreciate some clarity on that too :)

**Comment by MarcOverIP** [comment]
Can't answer that before I know a bit more about your situation. 

1. Do you have data in the rtops-* index and in redirhaproxy-* index? You can check via the Kibana 'Discover' view.
2. Is your Cobalt Strike listener configured to use a redirector?

On the redirector itself you do need to:

-  run the redir installer (its the redirs.tgz package that the initial installer created for you) 
- Configure HAProxy with a few specific settings regarding log setup.

Im in the midst of creating a wiki and adding more documentation, including on the redirector config. Do let me know if you are missing stuff at the wiki.

**Comment by MarcOverIP** [comment]
Closed due to inactivity.
