### ISSUE TITLE
Auto start dockers at boot

### ISSUE THREAD

**Issue by xychix** [outflanknl/RedELK#101]
Auto start dockers at boot

**Comment by xychix** [comment]
https://www.digitalocean.com/community/questions/how-to-start-docker-containers-automatically-after-a-reboot

post install fix:
docker update --restart unless-stopped container_id

**Comment by xychix** [comment]
"--restart unless-stopped"   is a flag we should add to each started container.

**Comment by xychix** [comment]
@fastlorenzo non issue? already set to 'ALWAYS' ?

**Comment by fastlorenzo** [comment]
should indeed already work with `always`, I think this can be closed

**Comment by MarcOverIP** [comment]
The internet fora are filled with people complaining this is not really working in all desired cases. But the ```always``` statement is the best Docker has to offer, so we go with that. Closing as this is already configured.
