### ISSUE TITLE
Simple search

### ISSUE THREAD

**Issue by xychix** [outflanknl/RedELK#103]
Please include (amongst others) c2.message in default search profile.

Meaning that a free format search would hit these fields.

**Comment by xychix** [comment]
- default Lucene zetten
- stack management -> advanced -> Query string options

van:
 { "analyze_wildcard": true  }
naar
{ "analyze_wildcard": true, "default_field":"*" }

**Comment by MarcOverIP** [comment]
This might be possible for KQL as well by changing the default_field setting per index in Stack Mngt -> Index Mngt -> Settings.

Need to test this further.

If possible I prefer to switch over to KQL given its fancy way of auto-complete during searching. If not possible, we should switch back to Lucene (Kibana advanced setting to set the default query language). Usability is more important than new features.

**Comment by fastlorenzo** [comment]
if it is a Kibana advanced setting, we should be able to set it from the json config during installation

**Comment by xychix** [comment]
note that my solution only works for Lucene. 
Marc is also chasing a KQL solution

**Comment by fastlorenzo** [comment]
Actually, doing it in the advanced settings didn't work for me (in elastic 7.10).
What worked however, is changing the ES index template settings for `default_field` from `[]` to `"*"`. 
Works for both `KQL` and `Lucene`:
![image](https://user-images.githubusercontent.com/768639/99157906-6cc60500-26cd-11eb-9e96-38c78810ca6e.png)
![image](https://user-images.githubusercontent.com/768639/99157937-ba427200-26cd-11eb-8136-15623c44bfd9.png)

**Comment by MarcOverIP** [comment]
I'm not sure this is the solution. Ive got a test environment where default_field is still set to [], and free search works in KQL.

I will merge PR #113 , but will leave this issue open until we've gotten to the bottom of this.
