### ISSUE TITLE
Migrate enrich script to new modular system

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#108]
The processing done in the enrich script should be moved as several modules of type `enrich` (similar to how it is done with alarms and connectors).

**Comment by fastlorenzo** [comment]
@xychix can we remove this part related to manual IOC (knowing that it's now possible to do it in the Kibana plugin)?

https://github.com/outflanknl/RedELK/blob/ff15843d40da5bdf47b777b0590c768b98edd871/elkserver/docker/redelk-base/redelkinstalldata/scripts/enrich.py#L380-L468

**Comment by MarcOverIP** [comment]
Please also look at items and follow-up discussion on issue #42 This specifically concerns: setting timezone in installer (possibly already done), /etc/redelk/known_testsystems.conf (can be removed) and destination.ip in logstash (can be removed)
