### ISSUE TITLE
Upgrade Elastic stack to 7.10

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#109]
Mainly performance improvements and compatibility for Kibana plugin (current version of the Kibana plugin has a quick fix for an issue that existed).

I've reviewed the changelog, shouldn't be any breaking changes for RedELK.

https://www.elastic.co/guide/en/elasticsearch/reference/current/release-highlights.html

**Comment by MarcOverIP** [comment]
Fixed in PR #112
