### ISSUE TITLE
Limit privileges or permission to user ?

### ISSUE THREAD

**Issue by coldalfred** [outflanknl/RedELK#11]
Thanks for this AWESOME project <3 FTW Elastic ELK

Hope you can help me with creating a user to only has read privileges to see example: Screenshots from some filters or scenario ? i don't know if that feature is already done.

Thanks

**Comment by MarcOverIP** [comment]
No not already done. Im also not really sure its rather easy to deploy. The free version of the ELK stack (which is installed by RedELK) does not support multiple users. Perhaps something can be done using the htaccess file and the nginx config on the redelk server, but I havent looked into it yet.

**Comment by coldalfred** [comment]
<3 that will be awesome, maybe something as a services ? or maybe using the Paid version.

And again thanks for your amazing work! if there is any coin address that we can donate in pro to the project will be great.

**Comment by MarcOverIP** [comment]
Ha, thanks. 

I believe you can simply upgrade a RedELK installation to a paid license of the ELK stack. That way you will have the possibilities for user access mngt within Kibana. Havent gone this route so arent totally sure.

Adding some basic user control is on our own wish list for a future version of RedELK. But dont expect that to be done soon.

We aren't looking into making RedELK a paid product. We just want to share this with the community and help those red and blue teams out there. If it really helps you in your work then a donation would be very kind. You can use either one of these:
BTC: 13h1mEkNUjy4PBUnHzG7sMDmbHtv9EUcds
LTC: LiXDkcLhwa2mhs2qdkEbceznpMPDzWRZx5

But a simple beer if we ever meet would also suffice :-)
