### ISSUE TITLE
New alarm: move Chameleon domain check to an alarm module

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#127]
The current setup with Chameleon should be migrated to an alarm module

**Comment by MarcOverIP** [comment]
Is this a duplicate of #131 or is this a different approach?

**Comment by fastlorenzo** [comment]
Linked to #131  indeed, Chameleon would be part of that alarm and thus should be moved in that specific alarm folder

**Comment by fastlorenzo** [comment]
@MarcOverIP we should close this one as this is the same as #131 (to avoid duplicate issues)
