### ISSUE TITLE
Cobalt Strike 3.14 logging format changed, breaks logstash filter rules

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#13]
Cobalt Strike version 3.14 changed a bit in the format of the logging. The logstash grok parsing rules in RedELK need to be updated to reflect the new logging of ver 3.14.

Currently, if you run RedELK with Cobalt Strike v3.14, the logs will be there, but there is no knowledge of sub fields. As a result, enrichment also fails.

**Comment by fastlorenzo** [comment]
Made a PR to fix this ( #15)
