### ISSUE TITLE
Alarms should include a identifier for the operation

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#133]
Alarms currently lack an identifier for which operation they originated from. The infra.attack_scenario is not sufficient, there should be another indicator that shows the name/ID of the entire operation (or client), not just the campaign within the operation.

Possibly this identifier should be added to the config.json file, and configured from there.

**Comment by fastlorenzo** [comment]
Agreed, this should be set in RedELK's config file (config.json) as a RedELK instance should be used only for one operation.
I'll see if I can make a quick PR for it, as it doesn't touch ES

**Comment by MarcOverIP** [comment]
Propose fix in PR #240

**Comment by MarcOverIP** [comment]
Fixed in PR #240
