### ISSUE TITLE
New alarm: alarm_genericlog

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#138]
New alarm, sort of a catch all, when'RedELK alarm' is written to an implant log or the c2 eventlog. Alarm should include the rest of that specific the log line. This allows the RT operator to script/develop implant actions that can trigger an alarm, have them freedom of what is included in the alarm, all without having to modify RedELK source code on alarm definitions.

**Comment by xychix** [comment]
Cool for first move after next working version :)

**Comment by MarcOverIP** [comment]
Fixed with #274
