### ISSUE TITLE
Move elastic data outside docker

### ISSUE THREAD

**Issue by xychix** [outflanknl/RedELK#139]
As far as I can tell the es data is inside the docker.
When having issues with a docker I'd like to purge them and rebuild/start them to get back in working order without loosing any data.

No files inside the docker should be changed while running (other than discardable files)

**Comment by MarcOverIP** [comment]
The data is in a docker storage volume, not inside a docker image. This is on purpose. You can nuke the image or even the container. Just point it to the storage volume and its all good. If you nuke the volume, its bad luck.

Alternative way would be to put the files on the host system outside of docker. But that brings along many other challenges.
