### ISSUE TITLE
ES template missing for some fields

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#142]
At least for the following fields:

**implantsdb:**
~~* host.geo.as.organization.name~~
~~* host.geo.as.organization.number~~

**rtops:**
~~* host.ip_int~~
~~* host.ip_ext~~
~~* host.ip~~
~~* host.geo.as.organization.name~~
~~* host.geo.as.organization.number~~

**.siem-signals:**
* agent.hostname
* c2.log.type
* c2.message
* c2.program
* c2.timestamp
* host.ip_int
* implant.id
* implant.log_file
* implant.task
* infra.attack_scenario
* infra.log.type
* input.type
* log.offset
~~* signal.rule.building_block_type~~
* signal.rule.exceptions_list
~~* signal.rule.filters~~
* signal.rule.risk_score_mapping
* signal.rule.rule_name_override
~~* signal.rule.severity_mapping~~
* signal.rule.throttle
~~* signal.rule.timestamp_override~~

**redirectortraffic-**
~~* alarm.alarm_httptraffic.last_alarmed (type date, example value: 2022-02-07T09:27:38.922562)~~
~~* alarm.alarm_httptraffic.last_checked (same as above)~~
~~* alarm.last_alarmed (same as above)~~
~~* alarm.last_checked (same as above)~~
~~* source.ip_otherproxies (text, can contain multiple IP values of chaining x-forwarded-for IP's)~~

**bluecheck**
~~* bluecheck (object)~~
~~* bluecheck.accountname (text)~~
~~* bluecheck.accountstate (text)~~
~~* bluecheck.certissuer (text)~~
~~* bluecheck.certsubject (test)~~
~~* bluecheck.message (text)~~
~~* bluecheck.pwchangedate (date)~~
~~* bluecheck.sectools (nested)~~
~~* bluecheck.sectools.ProcessID (text)~~
~~* bluecheck.sectools.Product (text)~~
~~* bluecheck.sectools.Vendor (text)~~
~~* bluecheck.sectoolsamount (integer)~~

**Comment by MarcOverIP** [comment]
Only siem-signals left. But this requires more work in accordance to the siem-signals defaults index.

**Comment by MarcOverIP** [comment]
Another few ones:
* c2.task_id
* c2.task_parameters
* implant.task_id
* implant.kill_date

**Comment by fastlorenzo** [comment]
@MarcOverIP what is still needed in this one?

**Comment by MarcOverIP** [comment]
Only siem-signals left.

**Comment by MarcOverIP** [comment]
Done.
