### ISSUE TITLE
ansible idempotent provisioning

### ISSUE THREAD

**Issue by DrMeosch** [outflanknl/RedELK#143]
Hi guys,

let me start a new feature here and help you with its implementation.
I have already an ansible role for redirs on my github account (+ molecule testing!).
I want to continue and write two more roles for teamservers and for the main redelk server, as well (with testing and idempotency).

At the end, all that you need to do is to fill some fields in the file `inventory` and run `ansible-playbook`.
Or, if you would like to reprovision your infrastructure, just change some variables and rerun `ansible-playbook`.

Does it sound good?

**Comment by fastlorenzo** [comment]
@DrMeosch I'm already maintaining 2 Ansible playbooks for that purpose:
- [RedELK Server playbook](https://github.com/fastlorenzo/redelk-server)
- [RedELK Client playbook](https://github.com/fastlorenzo/redelk-client) (works for teamservers and redirectors

**Comment by DrMeosch** [comment]
Perfect! I knew I've seen some info about the redelk ansible roles on twitter but I never seen they're implemented. Well done, and I definitely will check them out. Have a nice day, @fastlorenzo

**Comment by MarcOverIP** [comment]
Updated the readme and wiki to have this included. Closing now.
