### ISSUE TITLE
Add Neo4J back behind Nginx

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#144]
As a quick fix, Neo4J port is now exposed on the host IP directly (https://github.com/outflanknl/RedELK/pull/128/files/7099467526ea5deb04d242f8a9e3def0b243411c#diff-764ca6369634da98311d634d24ed1316a695d21a77ae054f13a76e59baba1abc).

We need to find a way to fix it and put it back behind Nginx.

**Comment by MarcOverIP** [comment]
Agree. But Neo4j and nginx documentation is not up to date / non working for this. So will probably take some time to better understand. 

For now low priority I would say. Neo4j webport still requires authentication.

**Comment by fastlorenzo** [comment]
done in #162
