### ISSUE TITLE
elkserver "limited" installation fails due to upstream Docker dependencies

### ISSUE THREAD

**Issue by drfinkus** [outflanknl/RedELK#148]
Installing elk server with the "limited" option fails due to an upstream dependency with `redelk-jupyter`, which is not supposed to be present in the limited deployment scenario. 

More specifically, the RedELK Nginx Docker image fails to start due to the aforementioned upstream dependency.

**Comment by fastlorenzo** [comment]
@drfinkus which version of RedELK are you using? In ´master´ branch, I don't see a reference to ´redelk-jupyter´ in the limited compose file: https://github.com/outflanknl/RedELK/blob/master/elkserver/redelk-limited.yml

**Comment by MarcOverIP** [comment]
I believe this is one of the (several) bugs in beta4. Master branch has this fixed. 

Im closing now. Feel free to reopen if you have experienced tis bug in master.
