### ISSUE TITLE
Consider configuring maximum docker logging size

### ISSUE THREAD

**Issue by xychix** [outflanknl/RedELK#151]
We have had several 'runaway' dockers eating full disk trough their log files. As usually the error behind it is something else there might be more to fix, but a verbose logging filling the entire disk never is usefull.

Can we set a config for that as mentioned here?

https://docs.docker.com/config/containers/logging/json-file/

**Comment by MarcOverIP** [comment]
Please correct me if Im wrong, but the proposed solution is eitehr one of following:

1. start container (docker run) with parameters. 
2. change the overall docker daemon settings. 

Option 1 does not exist for docker-compose, so we can't use that. 

Option 2 requires editing the daemon json file. Is there a docker config command for this, or do we need to to bring out the jq-fu for this?

**Comment by fastlorenzo** [comment]
Should be feasible in docker-compose file according to the [doc](https://docs.docker.com/compose/compose-file/compose-file-v3/#logging)

**Comment by fastlorenzo** [comment]
Added 2 options in `.env` file to set the max log size and max log files (in PR #157):

```
# Defines the maximum log size per container (https://docs.docker.com/compose/compose-file/compose-file-v3/#logging)
LOG_MAX_SIZE=200m
LOG_MAX_FILE=1
```
