### ISSUE TITLE
Screenshots are not loaded into RedELK with CobaltStrike 4.3

### ISSUE THREAD

**Issue by 0xS2V2** [outflanknl/RedELK#158]
This may be be cause CobaltStrike 4.3 is saving the screenshot files in a different way.

In CS 4.2, the middle part of the filename was 6 digits; `screen_043852_1733079596.jpg`.

In CS 4.3, the middle part is 8 hexa instead; `screen_e53cb8d3_759248274.jpg`

**Comment by MarcOverIP** [comment]
Did you pull master or did you use a specific release?

**Comment by 0xS2V2** [comment]
I am on `v2.0-beta2`, but I did look for changes regarding CS 4.3 in the master code base and did not find any.

**Comment by MarcOverIP** [comment]
We had to change this when 4.2 dropped (https://github.com/outflanknl/RedELK/blob/master/elkserver/docker/redelk-logstash/redelkinstalldata/redelk-main/scripts/cs_makescreenshotpath_beforecs4.2.rb)

Are you sure it changed *again* in CS4.3?

**Comment by MarcOverIP** [comment]
Just verified on a CS4.3 install and it seems the filename setup is the same as CS4.2. So I believe we already cover this. 

Closing this issue now. Feel free te reopen if you think I'm incorrect, or have a different issue with screenshots not coming through.
