### ISSUE TITLE
Logstash SSL issue

### ISSUE THREAD

**Issue by ashu2188** [outflanknl/RedELK#16]
I followed the instruction to set up redelk. I have my certificate based on ip address. I have kibana dashboard up but I don't see my team server logs getting populated. When I dig deeper in logs, I found logstash is having ssl issue.

`Caused by: javax.net.ssl.SSLHandshakeException: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE`

I added `ssl_verify_mode => none` in the 10-inputs.conf file but didn't help. Any tips?

**Comment by MarcOverIP** [comment]
Apologies for letting this unanswered for such a long time. Although we did discuss this a bit via Twitter, for some reason I wasn't notified about this post here on GitHub.

The error message you are receiving is a cryptic one, aa with any TLS error in logstash and filebeat. My guess is that either the info you put certs/config.cnf is incorrect, or that it wasnt correct in the first run and after running it a second time the new certs are not placed at the right locations on the redirecctors, teamservers and redelk server.

I'll be happy to help as this is an issue Ive encountered myself in the past, yet haven't found an easy way to solve

Could you post the certs/config.cnf you are using - mask the IP/DNS if you want?

Also, could you tell me if you at one time reran the initial-setup.sh and how you made sure the new certs are in place on the other systems?

**Comment by MarcOverIP** [comment]
Can you let me know if the issue is still relevant, or if you fixed it?

**Comment by MarcOverIP** [comment]
Closed issue due to inactivity. Do let us know if it is still relevant.
