### ISSUE TITLE
rsync command in getremotelogs.sh pulls from wrong directory

### ISSUE THREAD

**Issue by 78454674** [outflanknl/RedELK#199]
### Description

When deploying redelk from this repository the getremotelogs.sh will try to retrieve data from the folde /home/scponly/data instead of /home/scponly/cobaltsrike/data

The script in this repository https://github.com/outflanknl/RedELK/blob/7ea555882e40b5e7c199af89b5722c908be58408/elkserver/docker/redelk-base/redelkinstalldata/scripts/getremotelogs.sh#L24 seems to target the wrong location. 

But the cronjob https://github.com/outflanknl/RedELK/blob/7ea555882e40b5e7c199af89b5722c908be58408/c2servers/cron.d/redelk_cobaltstrike#L13 
target the  /home/scponly/cobaltsrike/ directory.

Which results in the following error:
```
root@testing-red-elk:~/elkserver/mounts# tail -f redelk-logs/getremotelogs.log
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
rsync: [Receiver] write error: Broken pipe (32)
receiving incremental file list
rsync: link_stat "/home/scponly/data" failed: No such file or directory (2)

sent 8 bytes  received 87 bytes  190.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
rsync: [Receiver] write error: Broken pipe (32)
```

## Expected beahviour
The getremotelogs.sh script pulls data from the  /home/scponly/cobaltsrike/ directory.

Do I miss some config option during install or is this a bug?

**Comment by MarcOverIP** [comment]
You seem to have caught a bug. Thank you for pointing out.

Quickest solution is to go back to a commit prior to August 27. Other solution is to wait till this bug is squashed (which likely will take a few days given my availability atm)

**Comment by MarcOverIP** [comment]
Actually, this went quicker than I thought. Fixed the bug in branch fix-issue-199-wrong-paths-in-rsync. It is awaiting feedback before merging into master. But if you want you can testrun that branch, or manually check what very little change I made.

Thanks again for bringing this to our attention!

**Comment by MarcOverIP** [comment]
Fixed in master
