### ISSUE TITLE
export_kibana_config script not parsing Kibana settings?

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#221]
It seems the kibana settings (``redelk_kibana_settings.json``) aren't exported and/or processed.

Im running the command: ``export_kibana_config.py --all --export --process --password=$redelkuserESpassword``

**Comment by fastlorenzo** [comment]
Correct, only the following objects are exported:
```python
self.kibana_objects = [
                "index-pattern",
                "search",
                "visualization",
                "dashboard",
                "map",
]
```

To change something in the settings, given how simple the format is (key/value), it's best to test it and then change manually in [`elkserver/docker/redelk-base/redelkinstalldata/templates/redelk_kibana_settings.json`](https://github.com/outflanknl/RedELK/blob/master/elkserver/docker/redelk-base/redelkinstalldata/templates/redelk_kibana_settings.json)
