### ISSUE TITLE
Kibana app upgrade to 7.16.

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#222]
Currently the Kibana app is at 7.10. With the ES stack moving to 7.16, this no longer works. Kibana app is currently disabled in installation. It would be great if we can include it again.

**Comment by fastlorenzo** [comment]
Done in https://github.com/fastlorenzo/redelk-kibana-app/releases/tag/v0.4.0-rc.1 and #241

**Comment by MarcOverIP** [comment]
Fixed in #241
