### ISSUE TITLE
JARM fingerprint aka JA3/S defense.

### ISSUE THREAD

**Issue by b4sh1t1** [outflanknl/RedELK#252]
Hello,

I'm wonder if RedELK can stop or obfuscate JARM fingerprint ( Client Hello packet: Version, Accepted Ciphers, List of Extensions, Elliptic Curves, and Elliptic Curve Formats )..since this is one of privacy we wont share it in our infrastructure.

https://miro.medium.com/max/1400/0*zZFKcFS-CkMtjUw1

The information they gathering in order as follows:
TLSVersion,Ciphers,Extensions,EllipticCurves,EllipticCurvePointFormats

So i wonder if there is some rules or configuration we could apply on TLS, SSL, cipher, application security to didn't exposed or share this information with them, or with "not trusted" sources.

or if we can obfuscate our SSL connections outbound on these fingerprint to Pivoting on them.

Thanks

**Comment by MarcOverIP** [comment]
I strongly advice to **not expose RedELK interfaces to the wide internet**. I recommend to filter access to these interfaces on IP level anyway.

Should you still want to expose those interfaces to the internet, and should you consider JARM fingerprinting an issue, than the best way to deal with this is by applying fixes for the known third party packages that RedELK uses for external interfaces: Filebeat, Logstash, Kibana and Nginx.

I'm closing this issue for now as per above reasoning. Feel free to reopen if you deem necessary.

**Comment by b4sh1t1** [comment]
Thanks mate,
Well this is 1st option to use in VPN or filtering access, but do you recommended to use this [tool](https://github.com/netskopeoss/jarm_randomizer) ?
