### ISSUE TITLE
Apache/nginx traffic not being parsed

### ISSUE THREAD

**Issue by carlneuhaus** [outflanknl/RedELK#254]
Since upgrading to Beta6 traffic from apache/nginx redirectors is not being parsed correctly in the Traffic dashboard. I can confirm that the log stash confirmation files `21-filter-redir-apache_logstash.conf` and `22-filter-redir-nginx_logstash.conf` are present in the redelk-logstash container at /usr/share/logstash/redelk-main/conf.d.

Apache and Nginx were setup according to the example files.
![Screen Shot 2022-04-28 at 10 17 20 am](https://user-images.githubusercontent.com/4409382/165651722-da44983d-7125-4c2c-8a3a-42a407800634.png)

Raw message being received from Apache
`[28/Apr/2022:00:09:01 +0000] redirector apache[24431]: frontend:www-http/::1:80 backend:c2 client:::1:35820 xforwardedfor:0.0.0.0 headers:{curl/7.77.0|redacted.com|0.0.0.0|https|-|-|-|} statuscode:503 request:GET /dpixel HTTP/1.1`

Raw message being received from Nginx
`[27/Apr/2022:18:27:54 +0000] redacted.com nginx[14734]: frontend:redir/::1:80 backend:decoy client:::1:35226 xforwardedfor:0.0.0.0 headers:{-|redacted.com|0.0.0.0|http|-|-|-|} statuscode:200 request:HEAD / HTTP/1.1`

**Comment by carlneuhaus** [comment]
This seems to be solved by using the logstash config files found in Main not in the release.
Fix may be related to #246

**Comment by MarcOverIP** [comment]
Yes good catch. The release is lagging a bit behind master. We should be pushing out a new release in not too long time. Closing this issue now.
