### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by pentest01** [outflanknl/RedELK#256]
I'm totally new to using ELK and SIEM tools. i followed the instructions and edited my config.cnf as follows

![image](https://user-images.githubusercontent.com/103268912/167752714-a74d6e3a-aae5-4a8d-a346-5eba906202f8.png)

but when i run ./initial-setup.sh certs/config.cnf, i get this. 

![image](https://user-images.githubusercontent.com/103268912/167752856-4b9edfbb-9587-40f2-bb8f-1c6bb9d9cff8.png)

and these new friends 

![image](https://user-images.githubusercontent.com/103268912/167753068-1eb7c8ff-0dc5-4748-8588-1abf57ef38ba.png)

i don't know if it's an error or i should proceed.

**Comment by fastlorenzo** [comment]
It looks like you forgot to change some values in config.cnf
Please double check (check for string MODIFYME) the file

**Comment by pentest01** [comment]
I changed those, and i got it up and running. But when i tried to use it on another server  still get greeted the same 

![image](https://user-images.githubusercontent.com/103268912/167898959-c40bc363-0d36-4d15-9254-c97446e6b220.png)

but when i run i still get same errors

![image](https://user-images.githubusercontent.com/103268912/167899095-3d7890e5-932e-45f6-8696-357db0877bee.png)

i thought it did all, i also followed this instruction on his blog post here: https://outflank.nl/blog/2020/02/28/redelk-part-2-getting-you-up-and-running/

the log wasn't much helpful, i want to know what i did wrong, so i can prevent in the future.

**Comment by MarcOverIP** [comment]
Those errors are from openssl. Not much we can do about.

I believe your value for CN is illegal. It does not allow a dot I believe.
