### ISSUE TITLE
Performance issue with rsync on C2server

### ISSUE THREAD

**Issue by sunnyneo** [outflanknl/RedELK#259]
I am facing performance issue with `rsync` cron job not terminating on the teamserver/C2server.

![image](https://user-images.githubusercontent.com/9748813/172031456-c4a16479-8df6-44ed-9246-6458e49c3577.png)

I am not familiar with `rsync` parameters but in the `https://github.com/outflanknl/RedELK/tree/master/elkserver/docker/redelk-base/redelkinstalldata/scripts/getremotelogs.sh`, it is `-rvx --append-verify` and it solved some performance issues I had earlier prior to the commit. 

In `https://github.com/outflanknl/RedELK/blob/master/c2servers/cron.d/redelk_cobaltstrike`, it is `-ax --delete`. After I switched to `-rvx --append-verify --delete` and it seems to solve my issue. However I am not sure if there is any side effect, as I don't see any issue for now.

**Comment by MarcOverIP** [comment]
Thank you for noticing. This issue seems to be emerging only recently. We fixed it only partly. You spotted the other rsync that we missed. Your proposed fix seems good at first sight. Fixed and merged.
