### ISSUE TITLE
Missing filebeat.yml

### ISSUE THREAD

**Issue by curi0usJack** [outflanknl/RedELK#26]
Hey guys,

I think there might be a bug in the install-c2server-cobaltstrike.sh script. I got a curious error when running the install routine. From the redelk-install.log file:

![image](https://user-images.githubusercontent.com/5608516/77237855-ade73300-6b99-11ea-8cc4-778f48b8783d.png)

I think the issue has to do with this block in the script itself:

![image](https://user-images.githubusercontent.com/5608516/77237595-acb50680-6b97-11ea-96dc-d4c9320a3bca.png)

When I changed it to set the destination path to filebeat.yml instead of just being copied as filebeat_cobatlstrike.yml, the routine worked. 

![image](https://user-images.githubusercontent.com/5608516/77260195-8608d580-6c54-11ea-8296-a76f4a95a34c.png)

Thanks for all the hard work!
Jason

**Comment by MarcOverIP** [comment]
Great catch. Thanks for letting me know Jason. Fixed (as well for PoshC2 installer) in commit 6a0ed86a04247323e09b7edfc90ecccc941c9323
