### ISSUE TITLE
Implant.log_file not showing c2logs

### ISSUE THREAD

**Issue by m7x** [outflanknl/RedELK#264]
Hi

First of all, great tool!

It looks like that `implant.log_file` field in Kibana is correctly populated, however, nginx can't load the log file because isn't there.  Looking at the code, it looks like the cron job (which was responsible of transferring the logs into web root) has been commented: 

https://github.com/outflanknl/RedELK/blob/master/elkserver/mounts/redelk-config/etc/cron.d/redelk#L15

Can I just re-enable that cron script and run it within the container? Would that solve the issue?

Thanks

**Comment by MarcOverIP** [comment]
Yes, you need to modify that line for your specific environment and uncomment. This is as intended ;-)
