### ISSUE TITLE
Issue with dashboards missing "keyword"

### ISSUE THREAD

**Issue by oribit** [outflanknl/RedELK#266]
Not sure if something specific of my deployment in AWS. But using Debian 11 and 2.0 BETA6, almost all dashboards doesn't work due a weird "issue" with the name of the fields. It seems the fields associated to the dashboards are named without "keyword":
![Screen Shot 2022-07-01 at 2 04 55 AM](https://user-images.githubusercontent.com/14796691/176798048-77be5dc2-9553-40a2-a126-20b771c189d4.png)

Changing the field used to the same named but with "keyword" at the end, fixes the problem.

**Comment by MarcOverIP** [comment]
I believe this happens when there is no data yet in ES. Might that be the case for you?

**Comment by oribit** [comment]
Yes, indeed that was exactly the case. There case a misconfiguration in our deployment and data was not ingested, so the first thought was this error that I fixed manually, so I can't say if this would be gone if the data ingestion works. I'll try to test it again with a clean installation. I'm going to close it, because it seems it could be our initial deployment. I'll open again if we face it again. Thanks!
