### ISSUE TITLE
ASN lookup in case of CDN not correct

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#27]
Both Apache and HAPRoxy logstash rules add ASN info to sourceip. However, when there is a CND involved, the wrong source field is used. Resulting in ASN info for the IP of the CDN instead of the real source (x-forwarded-for) address.

**Comment by DrMeosch** [comment]
Can confirm that I'm getting same results with nginx

**Comment by MarcOverIP** [comment]
Possibly fixed in commit 6e46bd82623bbf4097fe177f90b4415f988fa8b0 (maindev branch)
