### ISSUE TITLE
Remove config files from source control

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#283]
Configuration files should be removed from source control.
An example config file should be provided instead in source control.
The install script should take care of creating the config file from the example if it doesn't exist yet.

Identified configuration files to be removed:
- [ ] `certs/config.cnf`
- [ ] `elkserver/mounts/redelk-config/etc/redelk/config.json`
- [ ] `elkserver/mounts/redelk-config/etc/redelk/roguedomains.conf`

**Comment by fastlorenzo** [comment]
Create `.example` files and in the installer copy the `.example`file to the original file name (if not exists).
Then remove the original files from source control and add to .gitignore

**Comment by MarcOverIP** [comment]
Config files this applies to:
- [ ] certs/config.cnf
- [ ] elkserver/mounts/redelk-config/etc/cron.d/redelk
- [ ] elkserver/mounts/redelk-config/etc/redelk/config.json
- [ ] elkserver/mounts/redelk-config/etc/redelk/domainslist_redteam.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/iplist_alarmed.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/iplist_blueteam.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/iplist_customer.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/iplist_redteam.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/iplist_unknown.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/rogue_useragents.conf
- [ ] elkserver/mounts/redelk-config/etc/redelk/roguedomains.conf
- [ ] elkserver/mounts/redelk-logs/
- [ ] elkserver/mounts/redelk-ssh/
- [ ] elkserver/mounts/redelk-www/
- [ ] redirs/filebeat/filebeat.yml

**Comment by MarcOverIP** [comment]
Done with pr #294
