### ISSUE TITLE
asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:107:maxsize=2

### ISSUE THREAD

**Issue by xiongcancaom** [outflanknl/RedELK#29]
I'm execute commands: ./initial-setup.sh certs/config.cnf when appear this problem, I set is DNS1：redelk.totallynotavirus.nl.I'm a rookie. I'm asking for your help. Thank you

**Comment by MarcOverIP** [comment]
Hi there,

You need to modify the file in certs/config.cnf to include the DNS or IP of your RedELK server. You can find more info at the wiki (https://github.com/outflanknl/RedELK/wiki), or in this blog post (https://outflank.nl/blog/2020/02/28/redelk-part-2-getting-you-up-and-running/)
