### ISSUE TITLE
Nothing being indexed into implantsdb

### ISSUE THREAD

**Issue by RossLopez** [outflanknl/RedELK#299]
Using Cobaltstrike for C2, nothing being logged into the implantsdb index. Everything else is working (screenshots, credentials, etc). 
![Screenshot 2023-08-21 at 2 38 32 PM](https://github.com/outflanknl/RedELK/assets/10959913/c6d28ffe-1e42-4aab-94fe-283977727209)
![Screenshot 2023-08-21 at 2 42 15 PM](https://github.com/outflanknl/RedELK/assets/10959913/204fa072-266b-474c-a84d-dc77706a1a32)

**Comment by MarcOverIP** [comment]
What version are you using? Can you try with a clear/new search in Kibana's `Discover` (the real searching page) with no filters applied?

**Comment by MarcOverIP** [comment]
Closing due to lack of response.
