### ISSUE TITLE
help for install

### ISSUE THREAD

**Issue by meetgyn** [outflanknl/RedELK#30]
root@kronlab:/opt/ferramentas/tools/RedELK# ./initial-setup.sh
This script will generate necessary keys RedELK deployments
[X] ERROR missing parameter
[X] require 1st parameter: path of openssl config file
root@kronlab:/opt/ferramentas/tools/RedELK#

**Comment by MarcOverIP** [comment]
Give it the path to your openssl config file as paramater. Most likely certs/config.cnf. Make sure to edit that config file to match your infra.

More info on the wiki.
