### ISSUE TITLE
BounceBack redirector support

### ISSUE THREAD

**Issue by D00Movenok** [outflanknl/RedELK#306]
It would be nice if RedELK supported [BounceBack](https://github.com/D00Movenok/BounceBack) redirector. It has jsonl logs format that is easy to parse. If you need some additional logs, you may ask me for help.

**Comment by MarcOverIP** [comment]
Agree if would be great to add more tech components. But at this moment we are limited on time for devving on RedELK and like to stick to the original course. With support for Apache, Nginx and HAProxy I think we have covered most use cases at this moment. 

We do accept PRs. If you feel like making a PR, you can check the code related to the other proxies to see what is required, e.g. logstash rules, installers.

Im closing this issue now. But feel free to re-open if you need support with a PR.
