### ISSUE TITLE
Adding the user that initiated a task on the task log entry

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#34]
From the log file it is possible to correlate the `[input]` (which contains the user that created a task) and the related `[task]` entry.
I implemented it locally in logstash, I will create a PR when I have a bit more time.

One attention point is that it will query for the `[input]` entry with the same timestamp and beaconid, so multiple results could be found if 2 tasks are launched at the same exact time on the same beacon (which is normally less likely to happen).

**Comment by MarcOverIP** [comment]
I like the idea. We never had need for filtering down per user, but I guess it depends on workflow. And to be fair, it is really easy to filter the operator's name in the input line.

Im not sure about tying it to the input line as well. There is a reason that with CS we nowhere connect input with task or outputs: in our experience corner case such as you mention above actually do happen and happen more than we like to, including the situation when filebeat-logstash play catch up and ES hasnt stored the data yet. This results in parsing errors and overal lesser usability. 

Now if you know a way to make this 100% working correctly that would be great! If not, I still happily accept your PR for filtering the operator name in the input name.

I kindly ask you to develop against maindev branch. That branch will be version 2 of RedELK and has significant changes incl ES upgrade, renamed fields, neo4j and jupyter integration, etc. Should be stable enough for you start devving against in a few weeks time.

**Comment by fastlorenzo** [comment]
I'm currently investigating the [sleep plugin](https://www.elastic.co/guide/en/logstash/current/plugins-filters-sleep.html) to see if logstash can wait for a small amount of time for the input line to be processed before the input line. 
I'll test it for a while and if it's reliable I'll add it as a PR.

FYI I'm using RedELK with the latest version of ELK, I just needed to make some small changes in fields used by filebeat.

**Comment by MarcOverIP** [comment]
Im closing this right now. I've added a registration of the name of the red team operator per input in commit 3216a8f9697903dc1ad4517056af5e9cecb7f010

Feel free to reopen when you feel differently.
