### ISSUE TITLE
Adding additional dashboards

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#35]
It would be great to have several additional dashboard to show (for example):

- Tasks launched on all/a specific beacon
- Downloads
- Keystrokes
- Users connecting to CS
- TTPs used
- ...

I'm currently trying to create some of them, I will add them in a PR when they are stable.

**Comment by MarcOverIP** [comment]
👍 
Happy to see more of those. We create on the fly when needed. But I totally agree that the basic set should be upgraded and I happily accept PRs! 

The one thing that I really would like to have is way of visualising the MITRE ATT&CK ids in a logical way, preferably overlay on the Matrix. If not possibly directly from Kibana than via exporting and some parsing to make it a visualisation layer for the Matrix Navigator.

I kindly ask you to develop against maindev branch. That branch will be version 2 of RedELK and has significant changes incl ES upgrade, renamed fields, neo4j and jupyter integration, etc. Should be stable enough for you start devving against in a few weeks time.

**Comment by MarcOverIP** [comment]
In the current maindev branch there were many added. Closing for now.
