### ISSUE TITLE
New alarms

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#41]
I would like to see the following alarms added as part of alarm.py:
1. alarm for status change of domain classifications in bluecheck index. Alarm on any change!
2. alarm when a domain has a 'bad' classification. Bad is defined in the list that is already added as comment to alarm_check4 in alarm.py. This list of bad words comes from a review of classes defined by the domain checkers as currently supported by chameleon.py
3. alarm when an ip listed in /etc/redelk/iplist_blueteams.conf touches *any* part of our infra, so regardless of proxy destiantion. As one may have collected a list of egress IPs of blue teams during the years, this alarm may serve as an early warning for any type of investigation. Im not sure this list should be pre-populated as part of the RedELK package. But having the option to have alarms from a specific IP can be very useful
4. alarm when any connection is sent to proxy destionation 'alarm'. This is a hardcoded name. But is allows the red team operators to still get an alarm fromout redelk when specific logical on the redirector has determined this should get an alarm.

Desired modifications to alarm.py are:

5. when reading config files, adhere to comments mid-line. So stop reading after a \# character
6. be able to read IP subnets in config files and translate as such in ES queries. This should not be that hard as ES is IP and subnet aware.

**Comment by fastlorenzo** [comment]
PR #58 adds support for Microsoft Teams connector to send notifications

**Comment by fastlorenzo** [comment]
Let's make the following alarm names:
1. alarm_domainchange
2. alarm_baddomain
3. alarm_bttraffic
4. alarm_httpstatic

5. should be an enhancement of existing alarms
6. same as 5.

**Comment by xychix** [comment]
1,2,4 moved to separate issues.
