### ISSUE TITLE
Verify if can be cleaned or removed

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#42]
I wonder if we can remove the following:

1. Every installer sets the timezone at the beginning of the installation. Its hardcoded at Europe/Amsterdam right now, albeit via an easy to change variable. However, Im not sure its even necessary to set the timezone and I wonder if it can be removed as the time parsing in logstash seems to work OK.
2. I wonder if /etc/redelk/known_testsystems.conf serves any good. It once started as a way to detect sandboxes. But I believe the alarm on unknown IP c2 destination is more helpful, or a new alarm to an 'alarm' backend. Does this serve any purpose? Do people use it?
3. destination.ip in logstash' redirector config doesn't seem to be used. Can it be removed?

**Comment by fastlorenzo** [comment]
2. Indeed, and the issue with that file is also that it's case sensitive when querying ES, which is not always flagging test systems correctly
3. Personally not using it, the important thing for me is the source.ip and backend details

**Comment by fastlorenzo** [comment]
1.  Timezone should be part of the initial server setup, so before RedELK is installed, and up to the operator deploying it to choose which one to use.

**Comment by xychix** [comment]
Is this really a beta 4 milestone? or a nice to have?

**Comment by MarcOverIP** [comment]
Removal is always important and should be done asap imho. It would make sense to take this up in #108 . Are you willing to take this it up there?

**Comment by fastlorenzo** [comment]
Agreed, should be tackled as part of #108
