### ISSUE TITLE
Hardcode version nr docker images in install-elkserver.sh

### ISSUE THREAD

**Issue by MarcOverIP** [outflanknl/RedELK#48]
install-elkserver.sh now pulls the latest version of the docker images of neo4j and jupyter notebooks. We should set those to version numbers that we know that work.

**Comment by fastlorenzo** [comment]
Additionally, the `jupyter/scipy-notebook` image is 2.67GB, we should check if another smaller image exists:

**Comment by MarcOverIP** [comment]
Hardcoded the version of scipy-notebook in commit 4bdf2ef42fb22361a88edbe9d5235755d7788af9. Neo4j/BloodHound only has 1 release, so cant hardcode other than 'latest' which is the default.

Agree on the size of the jupyter notebook image. But I see this better resolved when we make the push to dockerise the entire RedELK package.

Closing for now. Happy to discuss the docker mage size in a different issue
