### ISSUE TITLE
Logging format required for Nginx?

### ISSUE THREAD

**Issue by lez0sec** [outflanknl/RedELK#51]
Really excited to read that, according to the latest release, support for Nginx has been added!

I have searched for any updates in the wiki and blog posts but I can only assume time hasn't allowed for that :)

Would you be able to share the config line to set Nginx to use the right logging format?

Thanks

**Comment by MarcOverIP** [comment]
Here you go: https://github.com/outflanknl/RedELK/blob/master/example-data-and-configs/nginx/redelk-redir-nginx.conf
