### ISSUE TITLE
Missing ES index templates

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#55]
The following ES index templates are missing:
- credentials
- bluecheck
- email

**Comment by MarcOverIP** [comment]
Fixed for bluecheck in commit dae7a31f2e122b8056dd5a50e71a9234627ef2e2

**Comment by MarcOverIP** [comment]
Sadly, some error and need to redo bluecheck ES index :-(

**Comment by MarcOverIP** [comment]
Fixed in #123
