### ISSUE TITLE
Kibana does not show target_user, target_hostname

### ISSUE THREAD

**Issue by nikonc** [outflanknl/RedELK#6]
Kibana does not show target_user, target_hostname,... at screenshots search. It only show at log metadata.
I don't understand how to have field target_user, target_hostname so screenshot log doesn't contain field to parse to target_user, target_hostname.
Hoping to hear from you soon.
![image](https://user-images.githubusercontent.com/44749265/47965696-a4c8f500-e07c-11e8-9d2b-d0073f86c994.png)

**Comment by smeetsie** [comment]
Im not entirely sure what you mean, but let me try to answer to the best of my ability. The screenshot does show target_user as well as target_hostname. Its just that target_ipint and beacon_id are in between. Overall, this is just the way Kibana represents this and luckily you can change this entirely to your liking. Perhaps this link https://www.elastic.co/guide/en/kibana/current/document-data.html will help you understand how you can move, add and remove columns in the overview.

**Comment by smeetsie** [comment]
No more reaction. Closing.
