### ISSUE TITLE
Migrate alarm_httptraffic to new format

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#74]

**Comment by xychix** [comment]
this should already have been done ;)

**Comment by fastlorenzo** [comment]
right, just noticed 😄 

nevertheless, it is still using a temp file for the alarmed IPs, should normally be done via an ES aggregated query to get rid of those temp files (bit like with the filehash alarm).

**Comment by xychix** [comment]
https://github.com/outflanknl/RedELK/commit/3fcff0f2bc3833fe53e1f49825148a0e787cb262
Fair enough.
one puzzle there. The tempfile is also used to update the iplist_unknown list using a cronjob. Good consideration of all functionality needed.

**Comment by fastlorenzo** [comment]
PR #83 adds some fixes, which should bring a stable version of this alarm

**Comment by xychix** [comment]
tnx and close
