### ISSUE TITLE
Migrate alarm_useragent to new format

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#75]

**Comment by fastlorenzo** [comment]
This alarm is missing initialization of the logger as well:
https://github.com/outflanknl/RedELK/blob/6446f741da0f8d6925270034f67d7ad3f5887798/elkserver/docker/redelk-base/redelkinstalldata/scripts/modules/alarm_useragent/module.py#L23-L25

**Comment by fastlorenzo** [comment]
Wrong query as well: https://github.com/outflanknl/RedELK/blob/6446f741da0f8d6925270034f67d7ad3f5887798/elkserver/docker/redelk-base/redelkinstalldata/scripts/modules/alarm_useragent/module.py#L56

**Comment by fastlorenzo** [comment]
Still using `print`:
https://github.com/outflanknl/RedELK/blob/6446f741da0f8d6925270034f67d7ad3f5887798/elkserver/docker/redelk-base/redelkinstalldata/scripts/modules/alarm_useragent/module.py#L66

**Comment by fastlorenzo** [comment]
Actually, it looks like the `run` method is there twice, maybe bad refactoring?

**Comment by xychix** [comment]
fixed
