### ISSUE TITLE
Add HTTPS to Nginx proxy

### ISSUE THREAD

**Issue by fastlorenzo** [outflanknl/RedELK#78]

**Comment by MarcOverIP** [comment]
My preference is to have this done with valid certificates, eg Letsencrypt. I see two options:
- Include certbot in the redelk-base image
- Look for a dockerized version of certbot.

As we are dockerizing themajority of roles on the elkserver, Im guessing it makes sense to have the letsencrypt dockerized as well.

Havent researched. There may be other options (nginx docker image with builtin certbot, Im just guessing here)

**Comment by fastlorenzo** [comment]
On the long run, I agree with the certbot approach.
We could use https://hub.docker.com/r/certbot/certbot/ (I used that in the past) to generate the certificates.
On the short run, I would use the elkserver certificates (for 2.0.0-beta.3), and provide an environment variable for the certificates path so the user can have 3 options:
1. use the RedELK self-signed certs
2. use the certbot container to get LE certificates
3. use a volume mount to use custom certs

**Comment by MarcOverIP** [comment]
I agree with the approach and to give users the option to choose. However, it has my preference to have this fully implemented before we merge this.

This will introduce some extra parameters in docker-compose file as well as installer script. We need to think on how t keep this as simple as possible.

**Comment by fastlorenzo** [comment]
PR #79 allows to provide different paths for the certificate. We could have a separate docker container handling certbot requests.
